item_images = {
    "Kokiri Sword": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Equipment\Kokiri-Sword.png",
    "Biggoron Sword": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Biggoron-Sword.png",  
    "Mirror Shield": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Equipment\Mirror-Shield.png",
    "Magic Meter": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Inventory\Magic_1.png",
    "Blue Fire Arrows": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\C-Items\Magic\Ice-Arrow.png",
    "Fire Arrows": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\C-Items\Magic\Fire-Arrow.png",
    "Light Arrows": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\C-Items\Magic\Light-Arrow.png",
    "Dins Fire": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\C-Items\Magic\Din-Fire.png",
    "Farores Wind": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\C-Items\Magic\Farore-Wind.png",
    "Lens of Truth": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\C-Items\Magic\Lens-of-Truth.png",
    "Slingshot": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\C-Items\Fairy-Slingshot.png",
    "Bomb Bag": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\C-Items\Bomb.png",
    "Rutos Letter": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\C-Items\Bottles\Letter.png",
    "Boomerang": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\C-Items\Boomerang.png",
    "Bow": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\C-Items\Fairy-Bow.png",
    "Megaton Hammer": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\C-Items\Megaton-Hammer.png",
    "Bottle": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\C-Items\Bottles\Empty-Bottle.png",
    "Progressive Hookshot": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\C-Items\Hookshot.png",
    "Longshot": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\C-Items\Longshot.png",
    "Progressive Scale": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Inventory\Silver-Scale.png",
    "Golden Scale": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Inventory\Golden-Scale.png",
    "Progressive Strength Upgrade": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Inventory\Goron-Bracelet.png",
    "Silver Gauntlet": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Inventory\Silver-Gauntlets.png",
    "Golden Gauntlet": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Inventory\Golden-Gauntlets.png",
    "Progressive Wallet": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Inventory\Adult-Wallet.png",
    "Goron Tunic": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Equipment\Goron-Tunic.png",
    "Zora Tunic": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Equipment\Zora-Tunic.png",
    "Hover Boots": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Equipment\Hover-Boots.png",
    "Iron Boots": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Equipment\Iron-Boots.png",
    "Zeldas Lullaby": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Songs\Zelda.png",
    "Eponas Song": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Songs\Epona.png",
    "Sarias Song": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Songs\Saria.png",
    "Suns Song": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Songs\Sun.png",
    "Song of Time": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Songs\Ocarina.png",
    "Song of Storms": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Songs\Storm.png",
    "Minuet of Forest": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Songs\Minuet.png",
    "Bolero of Fire": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Songs\Bolero.png",
    "Serenade of Water": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Songs\Serenade.png",
    "Requiem of Spirit": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Songs\Requiem.png",
    "Nocturne of Shadow": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Songs\Nocturne.png",
    "Prelude of Light": r"C:\Users\Kevin Hiemann\Desktop\Entwicklungen\Tracker_Ishizaki\images\Songs\Prelude.png",
}

orte = [ 
    "KF",
    "LW",
    "SFM",
    "HF",
    "LLR",
    "Market",
	"HC",
    "KV",
	"GY",
	"DMC",
	"DMT",
	"GC",
    "ZR",
    "LH",
    "ZD",
	"ZF",
	"GV",
    "GF",
	"HW",
    "Colo",
	"OGC",
    "IGC",
    "Deku",
    "DC",
    "JJ",
    "BotW",
    "Forest",
	"Fire",
    "Water",
	"Shadow",
	"Spirit",
    "IC",
    "GTG",
    "ToT",
		]