item_images = {
    "Kokiri Sword": r"images/Equipment/Kokiri-Sword.png",
    "Biggoron Sword": r"images/Biggoron-Sword.png",  
    "Mirror Shield": r"images/Equipment/Mirror-Shield.png",
    "Magic Meter": r"images/Inventory/Magic_1.png",
    "Blue Fire Arrows": r"images/C-Items/Magic/Ice-Arrow.png",
    "Fire Arrows": r"images/C-Items/Magic/Fire-Arrow.png",
    "Light Arrows": r"images/C-Items/Magic/Light-Arrow.png",
    "Dins Fire": r"images/C-Items/Magic/Din-Fire.png",
    "Farores Wind": r"images/C-Items/Magic/Farore-Wind.png",
    "Lens of Truth": r"images/C-Items/Magic/Lens-of-Truth.png",
    "Slingshot": r"images/C-Items/Fairy-Slingshot.png",
    "Bomb Bag": r"images/C-Items/Bomb.png",
    "Rutos Letter": r"images/C-Items/Bottles/Letter.png",
    "Boomerang": r"images/C-Items/Boomerang.png",
    "Bow": r"images/C-Items/Fairy-Bow.png",
    "Megaton Hammer": r"images/C-Items/Megaton-Hammer.png",
    "Bottle": r"images/C-Items/Bottles/Empty-Bottle.png",
    "Progressive Hookshot": r"images/C-Items/Hookshot.png",
    "Longshot": r"images/C-Items/Longshot.png",
    "Progressive Scale": r"images/Inventory/Silver-Scale.png",
    "Golden Scale": r"images/Inventory/Golden-Scale.png",
    "Progressive Strength Upgrade": r"images/Inventory/Goron-Bracelet.png",
    "Silver Gauntlet": r"images/Inventory/Silver-Gauntlets.png",
    "Golden Gauntlet": r"images/Inventory/Golden-Gauntlets.png",
    "Progressive Wallet": r"images/Inventory/Adult-Wallet.png",
    "Goron Tunic": r"images/Equipment/Goron-Tunic.png",
    "Zora Tunic": r"images/Equipment/Zora-Tunic.png",
    "Hover Boots": r"images/Equipment/Hover-Boots.png",
    "Iron Boots": r"images/Equipment/Iron-Boots.png",
    "Zeldas Lullaby": r"images/Songs/Zelda.png",
    "Eponas Song": r"images/Songs/Epona.png",
    "Sarias Song": r"images/Songs/Saria.png",
    "Suns Song": r"images/Songs/Sun.png",
    "Song of Time": r"images/Songs/Ocarina.png",
    "Song of Storms": r"images/Songs/Storm.png",
    "Minuet of Forest": r"images/Songs/Minuet.png",
    "Bolero of Fire": r"images/Songs/Bolero.png",
    "Serenade of Water": r"images/Songs/Serenade.png",
    "Requiem of Spirit": r"images/Songs/Requiem.png",
    "Nocturne of Shadow": r"images/Songs/Nocturne.png",
    "Prelude of Light": r"images/Songs/Prelude.png",
}

orte = [ 
    "KF",
    "LW",
    "SFM",
    "HF",
    "LLR",
    "Market",
	"HC",
    "KV",
	"GY",
	"DMC",
	"DMT",
	"GC",
    "ZR",
    "LH",
    "ZD",
	"ZF",
	"GV",
    "GF",
	"HW",
    "Colo",
	"OGC",
    "IGC",
    "Deku",
    "DC",
    "JJ",
    "BotW",
    "Forest",
	"Fire",
    "Water",
	"Shadow",
	"Spirit",
    "IC",
    "GTG",
    "ToT",
		]